# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: application

data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop

  labels:
    component: cart
    project: roboshop
    tier: application

spec:
  replicas: 1

  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: application

  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: application

    spec:
      containers:
      - name: cart
        image: sangala2025/cart:v1
        resources:
          requests:
            cpu: "50m"
            memory: "120Mi"

          limits:
            cpu: "100m"
            memory: "256Mi"

        envFrom:
        - configMapRef:
            name: cart

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop

  labels:
    component: cart
    project: roboshop
    tier: application

spec:

  selector:
    component: cart
    project: roboshop
    tier: application

  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20